# ruff: noqa
fake_news_response = {
    "status": "ok",
    "totalResults": 4107,
    "articles": [
        {
            "source": {"id": "bbc-news", "name": "BBC News"},
            "author": "https://www.facebook.com/bbcnews",
            "title": "Australian man fined for taking pet snake surfing",
            "description": "Wildlife officers say the man endangered Shiva the snake and breached his permit to keep her.",
            "url": "https://www.bbc.co.uk/news/world-australia-66816893",
            "urlToImage": "https://ichef.bbci.co.uk/news/1024/branded_news/523B/production/_131115012_shiva5.jpg",
            "publishedAt": "2023-09-18T06:10:40Z",
            "content": "A Gold Coast man who filmed himself taking his pet snake for a surf has been fined by Australian wildlife authorities.\r\nHigor Fiuza and his bredli carpet python Shiva became local celebrities earlier… [+1679 chars]",
        },
        {
            "source": {"id": None, "name": "Slashdot.org"},
            "author": "EditorDavid",
            "title": "IEEE Specctrum Announces Top Programming Languages of 2023: Python and SQL",
            "description": 'Last week IEEE Spectrum released its 10th annual rankings of the Top Programming Languages.\nIt choose a top language for each of three categories: actively used among typical IEEE members and working software engineers, in demand by employers, or "in the zeit…',
            "url": "https://developers.slashdot.org/story/23/09/11/023222/ieee-specctrum-announces-top-programming-languages-of-2023-python-and-sql",
            "urlToImage": "https://a.fsdn.com/sd/topics/programming_64.png",
            "publishedAt": "2023-09-11T07:34:00Z",
            "content": "Last week IEEE Spectrum released its 10th annual rankings of the Top Programming Languages.\r\nIt choose a top language for each of three categories: actively used among typical IEEE members and workin… [+2800 chars]",
        },
        {
            "source": {"id": None, "name": "Github.com"},
            "author": "mimseyedi",
            "title": "Pysentation – The Python Presentation",
            "description": "pysentation is a CLI for displaying Python presentations. - GitHub - mimseyedi/pysentation: pysentation is a CLI for displaying Python presentations.",
            "url": "https://github.com/mimseyedi/pysentation",
            "urlToImage": "https://opengraph.githubassets.com/c77239934d7f7d10cf57a49337afdfda1ef3436dfd7e83fa4b1ec916ca048a37/mimseyedi/pysentation",
            "publishedAt": "2023-09-01T17:02:58Z",
            "content": "Table of Contents: \r\nIntroduction \r\npysentation is a CLI for displaying Python presentations.\r\npysentation, by taking a Python file written with simple but specific rules, can convert the contents of… [+13258 chars]",
        },
        {
            "source": {"id": None, "name": "Hackaday"},
            "author": "Bryan Cockfield",
            "title": "PyOBD Gets Python3 Upgrades",
            "description": "One of the best things about open source software is that, instead of being lost to the ravages of time like older proprietary software, anyone can dust off an old open source program and bring it …",
            "url": "https://hackaday.com/2023/09/17/pyobd-gets-python3-upgrades/",
            "urlToImage": "https://hackaday.com/wp-content/uploads/2023/09/obd-main.jpg",
            "publishedAt": "2023-09-17T14:00:00Z",
            "content": "One of the best things about open source software is that, instead of being lost to the ravages of time like older proprietary software, anyone can dust off an old open source program and bring it up… [+1241 chars]",
        },
        {
            "source": {"id": None, "name": "The State"},
            "author": "Mark Price",
            "title": "Python found parked outside Walmart in South Carolina and jokes erupt on social media",
            "description": "“Glad it didn’t crawl up into someone vehicle.”",
            "url": "https://www.thestate.com/news/state/south-carolina/article279462804.html",
            "urlToImage": "https://media.zenfs.com/en/the_state_mcclatchy_264/1b8903cbf14231f279a0388aee0e16e9",
            "publishedAt": "2023-09-18T11:30:59Z",
            "content": "African pythons can be officially added to the list of odd things you may find parked outside Walmart in South Carolina.\r\nOne was caught at the Walmart Supercenter on Gentry Memorial Highway in Picke… [+1367 chars]",
        },
        {
            "source": {"id": "abc-news", "name": "ABC News"},
            "author": "ABC News",
            "title": "WATCH: Australian surfer takes pet python along for a ride",
            "description": "A surfer with a pet python decided to take the reptile out for a spin on his board, with drone footage showing the pair enjoying the waves in the sunshine.",
            "url": "https://abcnews.go.com/International/video/australian-surfer-takes-pet-python-ride-102954070",
            "urlToImage": "https://i.abcnewsfe.com/a/6cb0dcde-3311-49a5-b562-be5ed05d5327/230906_abc_social_surfer_hpMain_9x16.jpg?w=992",
            "publishedAt": "2023-09-06T09:07:43Z",
            "content": "<ul><li>Whats next for Russia? \r\n</li><li>What comes next after Texas school shooting?\r\n</li><li>What's next for abortion rights in America?\r\n</li><li>The new battle for voting rights\r\n</li><li>How w… [+2322 chars]",
        },
        {
            "source": {"id": "business-insider", "name": "Business Insider"},
            "author": "Jenny McGrath",
            "title": "Burmese pythons are being spotted farther and farther north in Florida and could reach other states, experts warn. 'It really does feel like an alien invasion,' one scientist said.",
            "description": "It only took Burmese pythons a few decades to wipe out wildlife populations in the Florida Everglades. The same could happen in northern states.",
            "url": "https://www.businessinsider.com/burmese-pythons-could-devastate-northern-us-states-2023-9",
            "urlToImage": "https://i.insider.com/64f7bfcf1b7ced0019c8a3b4?width=1200&format=jpeg",
            "publishedAt": "2023-09-07T19:34:38Z",
            "content": "A Burmese python sits in the grass at Everglades Holiday Park in Fort Lauderdale, Florida.Rhona Wise/AFP via Getty Images\r\n<ul>\n<li>Burmese pythons are an incredibly destructive invasive species in F… [+8226 chars]",
        },
        {
            "source": {"id": None, "name": "Github.io"},
            "author": None,
            "title": "Playing with Genetic Algorithms in Python",
            "description": "A long long time ago I was young and going to school to attend a Computer Science program. It was so long ago that the data structures course was done in C++ and Java was shown to us as the new kid on the block.",
            "url": "https://joseprupi.github.io/misc/2023/08/19/playing_with_genetic_algorithms_in_python.html",
            "urlToImage": None,
            "publishedAt": "2023-09-06T16:57:52Z",
            "content": "A long long time ago I was young and going to school to attend a Computer Science program. It was so long ago that the data structures course was done in C++ and Java was shown to us as the new kid o… [+6487 chars]",
        },
        {
            "source": {"id": None, "name": "Lwn.net"},
            "author": None,
            "title": "Altering Python attribute handling for modules",
            "description": "A recent discussion on the Python forum looked at a way to\nprotect module objects (and users) from mistaken attribute assignment and\ndeletion. \nThere are ways \nto get the same effect today, but the mechanism that would be used causes a\nperformance penalty for…",
            "url": "https://lwn.net/SubscriberLink/943619/eaa8a4496fcba1fd/",
            "urlToImage": None,
            "publishedAt": "2023-09-11T08:27:31Z",
            "content": "<table><tr><td>Welcome to LWN.net\r\nThe following subscription-only content has been made available to you \r\nby an LWN subscriber. Thousands of subscribers depend on LWN for the \r\nbest news from the L… [+8414 chars]",
        },
        {
            "source": {"id": None, "name": "Boing Boing"},
            "author": "David Pescovitz",
            "title": "Python cowboy boots, Leica camera, cars, and too many water bottles at Pittsburgh airport auction",
            "description": "On October 7, the Pittsburgh International Airport will host its annual auction of crap that people left behind and was never claimed. The items include fancy cameras, designer handbags, countless water bottles, stacks of books, and apparently almost a dozen …",
            "url": "https://boingboing.net/2023/09/26/python-cowboy-boots-leica-camera-cars-and-too-many-water-bottles-at-pittsburgh-airport-auction.html",
            "urlToImage": "https://i0.wp.com/boingboing.net/wp-content/uploads/2023/09/53172301457-c13a6ffee6-k.webp?fit=1000%2C667&ssl=1",
            "publishedAt": "2023-09-26T23:50:18Z",
            "content": "On October 7, the Pittsburgh International Airport will host its annual auction of crap that people left behind and was never claimed. The items include fancy cameras, designer handbags, countless wa… [+1045 chars]",
        },
        {
            "source": {"id": None, "name": "Hackaday"},
            "author": "Al Williams",
            "title": "Cheap LCD Uses USB Serial",
            "description": "Browsing the Asian marketplaces online is always an experience. Sometimes, you see things at ridiculously low prices. Other times, you see things and wonder who is buying them and why …read more",
            "url": "https://hackaday.com/2023/09/11/cheap-lcd-uses-usb-serial/",
            "urlToImage": "https://hackaday.com/wp-content/uploads/2023/09/PXL_20230906_172618982.MP__featured.png",
            "publishedAt": "2023-09-11T17:00:41Z",
            "content": "Browsing the Asian marketplaces online is always an experience. Sometimes, you see things at ridiculously low prices. Other times, you see things and wonder who is buying them and why — a shrimp pill… [+5443 chars]",
        },
        {
            "source": {"id": None, "name": "Github.com"},
            "author": "pwwang",
            "title": "Toml-bench – Which toml package to use in Python?",
            "description": "Which toml package to use in python? Contribute to pwwang/toml-bench development by creating an account on GitHub.",
            "url": "https://github.com/pwwang/toml-bench",
            "urlToImage": "https://opengraph.githubassets.com/4bb5259f6f52b370950ff19b2d7dd76e7d843ad4fbdc91af7bfa7e88a0906a26/pwwang/toml-bench",
            "publishedAt": "2023-09-02T15:13:06Z",
            "content": "Which toml package to use in python?\r\nSee also: toml-lang and PEP 680\r\nReport\r\nVersion\r\nThe verions of the packages tested in this report.\r\nDumping None value\r\nHow the package dumps None value in pyt… [+7911 chars]",
        },
        {
            "source": {"id": None, "name": "Github.com"},
            "author": "zqqqqz2000",
            "title": "Shshsh is a bridge connects Python and shell",
            "description": "a bridge between python and shell. Contribute to zqqqqz2000/shshsh development by creating an account on GitHub.",
            "url": "https://github.com/zqqqqz2000/shshsh",
            "urlToImage": "https://opengraph.githubassets.com/b066b51f0f6c80f0c4b52db8938ca291eeecffe34e8120d9daa6925c2563177c/zqqqqz2000/shshsh",
            "publishedAt": "2023-09-23T07:18:39Z",
            "content": "Shshsh is a bridge connects python and shell.\r\n<ul><li>A simple way to write shell in python.</li><li>Flexable.</li><li>Support directly chain a python function in pipe.</li></ul>To install shshsh wi… [+1880 chars]",
        },
        {
            "source": {"id": None, "name": "Github.com"},
            "author": "ArthurFerreira2",
            "title": "ReinetteII+.py, an Apple II plus emulator in Python",
            "description": "Apple II emulator in python. Contribute to ArthurFerreira2/reinette-II-plus-dot-py development by creating an account on GitHub.",
            "url": "https://github.com/ArthurFerreira2/reinette-II-plus-dot-py",
            "urlToImage": "https://opengraph.githubassets.com/aedbe97c286fa449dea87ecc93ffe6e137dba17976b4a137ca03b3e9530eaaf5/ArthurFerreira2/reinette-II-plus-dot-py",
            "publishedAt": "2023-09-19T19:47:49Z",
            "content": "An easy to use, yet efficient, Apple II plus emulator in python\r\nFeatures\r\n<ul><li>Language Card (64KB of RAM)</li><li>All video modes at 30 fps</li><li>window resize by integer factors</li><li>Singl… [+1302 chars]",
        },
        {
            "source": {"id": None, "name": "Modular.com"},
            "author": None,
            "title": "How Mojo gets a 35,000x speedup over Python – Part 2",
            "description": "We are building a next-generation AI developer platform for the world. Read our latest post on how How Mojo gets a 35,000x speedup over Python – Part 2",
            "url": "https://www.modular.com/blog/how-mojo-gets-a-35-000x-speedup-over-python-part-2",
            "urlToImage": "https://assets-global.website-files.com/64174a9fd03969ab5b930a08/64ecd4c8eacd016afd57b421_chuttersnap-eH_ftJYhaTY-unsplash.jpg",
            "publishedAt": "2023-08-29T13:07:00Z",
            "content": "In the previous blog post, we motivated the Mandelbrot set problem and described basic optimization techniques to get around 90x speedup over Python. In this blog post (part 2 of our 3 part blog post… [+12709 chars]",
        },
    ],
}
